# Log changes but don't actually do anything
dry_run: false
# Interact with third-party API's
third_party_apis: true

redis:
  url: "redis://localhost:6379/0"

sentry:
  url: # set in settings.local.yml

google:
  domain: biola.edu
  usage_report:
    # You'd think you could just set this to today but it seems like you get errors like
    # "Data for dates later than ______ is not yet available" unless you back about 2-3 days
    # See https://developers.google.com/admin-sdk/reports/v1/reference/userUsageReport/get
    days_ago: 3
  api_client:
    application_name: google-syncinator
    application_version: '0.1.0'
    key_path: # set in settings.local.yml
    secret: # set in settings.local.yml
    scopes:
      - "https://www.googleapis.com/auth/admin.directory.user"
      - "https://www.googleapis.com/auth/admin.directory.group"
      - "https://www.googleapis.com/auth/admin.directory.group.member"
      - "https://www.googleapis.com/auth/admin.reports.usage.readonly"
    issuer: # set in settings.local.yml
    person: # set in settings.local.yml

trogdir:
  scheme: http
  host: trogdir-api.dev
  port:
  script_name:
  version: v1
  access_id: # set in settings.local.yml
  secret_key: # set in settings.local.yml
  api_timeout: 300 # 5 min

ws:
  db:
    adapter: mysql2
    host: # set in settings.local.yml
    database: ws
    user: # set in settings.local.yml
    password: # set in settings.local.yml
    reconnect: true

# See http://rdoc.info/github/mikel/mail/Mail#defaults-class_method
email:
  from: no-reply@biola.edu
  delivery_method: test
  options: {}

# all times should be in seconds
deprovisioning:
  # period to protect new accounts from being deprovisioned
  protect_for: 2592000 # 30 days
  inactive_after: 31557600 # 1 year
  reusable_after: 15552000 # 6 months
  schedules:
    # typically alumni only
    allowed:
      never_active:
        - 432000 # 5 days
        - :suspend
        - 15552000 # 6 months
        - :delete
      inactive:
        - 432000 # 5 days
        - :notify_of_inactivity
        - 2332800 # 27 days
        - :notify_of_inactivity
        - 259200 # 3.days
        - :suspend
        - 15552000 # 6 months
        - :delete
    # typically those with no affiliations
    unallowed:
      never_active:
        - 432000 # 5 days
        - :delete
      active:
        - 432000 # 5 days
        - :notify_of_closure
        - 604800 # 1 week
        - :suspend
        - 15552000 # 6 months
        - :delete

affiliations:
  # affiliations that get a john.doe style email
  employeeish:
    - employee
    - trustee
    - faculty
    - other
    - faculty emeritus
  # affiliations that get a john.h.doe style email
  studentish:
    - student
  # these affiliations are required to have an email address
  email_required:
    - employee
    - trustee
    - faculty
    - other
    - faculty emeritus
    - student
  # these affiliations are allowed but not required to have an email address
  email_allowed:
    - alumnus

groups:
  whitelist:
    - Alpha 1st East
    - Alpha 1st West
    - Alpha 2nd East
    - Alpha 2nd West
    - Alpha 3rd East
    - Alpha 3rd West
    - Beachcomber 1st
    - Beachcomber 2nd
    - Biola House
    - Calpella House 2
    - Calpella House
    - Emerson 1st Even
    - Emerson 1st Odd
    - Emerson 2nd Even
    - Emerson 2nd Odd
    - Fairvilla House
    - Figueras House
    - Gardenhill House
    - Hart 1st Even
    - Hart 1st Odd
    - Hart 2nd Even
    - Hart 2nd Odd
    - Hope 1st North
    - Hope 1st South
    - Hope 2nd North
    - Hope 2nd South
    - Hope 3rd North
    - Hope 3rd South
    - Hope 4th North
    - Hope 4th South
    - Horton 1st North
    - Horton 1st South
    - Horton 2nd North
    - Horton 2nd South
    - Horton 3rd North
    - Horton 3rd South
    - Horton 4th North
    - Horton 4th South
    - Horton 5th North
    - Horton 5th South
    - La Mirada 1st
    - La Mirada 2nd
    - Li 1st
    - Li 2nd
    - Li 3rd
    - Lido Mirada 1st
    - Lido Mirada 2nd
    - Philosophy House
    - Ranch 1st
    - Rosecrans 1 1st
    - Rosecrans 1 2nd
    - Rosecrans 2 1st
    - Rosecrans 2 2nd
    - Rosecrans 3 1st
    - Rosecrans 3 2nd
    - Rosecrans 4 1st
    - Rosecrans 4 2nd
    - Rosecrans 5 1st
    - Rosecrans 5 2nd
    - Sigma 1st Long
    - Sigma 1st Short
    - Sigma 2nd Long
    - Sigma 2nd Short
    - Sigma 3rd Long
    - Sigma 3rd Short
    - Springford House
    - Stewart 1st Back Suites
    - Stewart 1st Front Suites
    - Stewart 1st North Quads
    - Stewart 1st South Quads
    - Stewart 2nd Back Suites
    - Stewart 2nd Front Suites
    - Stewart 2nd North Quads
    - Stewart 2nd South Quads
    - Thompson 1st Even
    - Thompson 1st Odd
    - Thompson 2nd Even
    - Thompson 2nd Odd
    - Thompson 3rd Even
    - Thompson 3rd Odd
    - Tradewinds 1st
    - Tradewinds 2nd
    - Tropicana 1st
    - Tropicana 2nd
    - Welch 1st
    - Welch 2nd
    - Welch 3rd
    - Whiterock House
